input_dir: /Volumes/The_DollMaker/2026/00 - Kirtan Teg Singh/04 - SGGS/Volumen 1 -
  Dawn/03 - Sri Raag/unified/01
output_dir: /Volumes/The_DollMaker/2026/00 - Kirtan Teg Singh/04 - SGGS/Volumen 1
  - Dawn/03 - Sri Raag/unified/01
plugin_path: /Library/Audio/Plug-Ins/Components/Lurssen Mastering EQ v6.component
use_plugin: true
preset: Electronic
input_drive: 4.8
push: 3.2
presence: 3.5
loudness_target: -14.0
true_peak: -1.0
bitrate: 256k
suffix: _MONO_LURSSEN
jobs: 2
overwrite: false
verbose: true
